version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=host.docker.internal
    env_file:
      - .env
      
  worker:
    build: .
    command: python -m app.queue.worker
    environment:
      - REDIS_HOST=host.docker.internal
    env_file:
      - .env
  